# Generated by Django 6.0.3 on 2026-09-01 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='client',
            new_name='client_id',
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('image', models.ImageField(blank=True, db_column='IMAGE', null=True, upload_to='site_images/')),
                ('site', models.ForeignKey(db_column='SITE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='client.site')),
            ],
            options={
                'db_table': 'POC_SITE_IMAGE',
            },
        ),
    ]
