# Generated by Django 6.0.3 on 2026-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_client_site_client_id_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, db_column='PHOTO', null=True, upload_to='client_photos/'),
        ),
    ]
