# Generated by Django 6.0.3 on 2026-10-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_sites',
            field=models.ManyToManyField(blank=True, related_name='assigned_clients', to='client.site'),
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('SUBCONTRACTOR', 'Subcontractor')], db_column='ROLE', default='ADMINISTRATOR', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_column='STATUS', default='ACTIVE', max_length=255),
        ),
    ]
