# Generated by Django 6.0.3 on 2026-09-18 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_site_assigned_contractors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='assigned_contractors',
        ),
        migrations.AddField(
            model_name='site',
            name='assigned_contractor',
            field=models.ForeignKey(blank=True, db_column='ASSIGNED_CONTRACTOR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contractor', to=settings.AUTH_USER_MODEL),
        ),
    ]
