# Generated by Django 6.0.3 on 2026-10-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_assigned_sites_client_role_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('SUBCONTRACTOR', 'Subcontractor')], db_column='ROLE', max_length=255),
        ),
    ]
