# Generated by Django 6.0.3 on 2026-09-18 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_site_assigned_contractors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='assigned_contractor',
            field=models.ForeignKey(blank=True, db_column='ASSIGNED_CONTRACTOR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contractors', to=settings.AUTH_USER_MODEL),
        ),
    ]
