# Generated by Django 6.0.3 on 2026-10-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_role'),
        ('client', '0007_alter_site_assigned_contractor'),
    ]

    operations = [
    ]
