# Generated by Django 6.0.3 on 2026-09-22 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_alter_serviceschedule_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteWork',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('MISSED', 'MISSED')], db_column='STATUS', default='IN_PROGRESS', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, db_column='CHECK_IN_TIME', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, db_column='CHECK_OUT_TIME', null=True)),
                ('completion_notes', models.TextField(blank=True, db_column='COMPLETION_NOTES', null=True)),
                ('location', models.CharField(blank=True, db_column='LOCATION', max_length=255, null=True)),
                ('completed_by', models.ForeignKey(db_column='COMPLETED_BY', on_delete=django.db.models.deletion.CASCADE, related_name='work_completions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.OneToOneField(db_column='SCHEDULE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='work_completion', to='schedule.serviceschedule')),
            ],
            options={
                'db_table': 'POC_Complete_Work',
            },
        ),
        migrations.CreateModel(
            name='WorkCompleteImage',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_photo', models.ImageField(blank=True, db_column='EVIDENCE_PHOTO', null=True, upload_to='work_evidence/')),
                ('work_completion', models.ForeignKey(db_column='WORK_ID', on_delete=django.db.models.deletion.CASCADE, related_name='work_completion_images', to='work.completework')),
            ],
            options={
                'db_table': 'POC_WORK_COMPLETE_IMAGE',
            },
        ),
    ]
