# Generated by Django 6.0.3 on 2026-09-18 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_site_assigned_contractors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_column='SCHEDULED_DATE')),
                ('scheduled_time', models.TimeField(db_column='SCHEDULED_TIME')),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('COMPLETED', 'COMPLETED'), ('MISSED', 'MISSED'), ('CANCELLED', 'CANCELLED')], db_column='STATUS', default='SCHEDULED', max_length=255)),
                ('notes', models.TextField(blank=True, db_column='NOTES', null=True)),
                ('created_by', models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.CASCADE, related_name='created_service_schedules', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(db_column='SITE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='client.site')),
            ],
            options={
                'db_table': 'POC_SERVICE_SCHEDULE',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
    ]
