# Generated by Django 6.0.3 on 2026-09-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceschedule',
            options={},
        ),
    ]
