# Generated by Django 6.0.3 on 2026-09-01 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_userdetail_phone_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='DELETED_AT', null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='is_deleted',
            field=models.BooleanField(db_column='IS_DELETED', default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UPDATED_AT'),
        ),
    ]
