# Generated by Django 6.0.3 on 2026-09-26 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0007_alter_site_assigned_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_column='INVOICE_NUMBER', max_length=255, unique=True)),
                ('invoice_date', models.DateField(db_column='INVOICE_DATE')),
                ('service_period_start', models.DateField(db_column='SERVICE_PERIOD_START')),
                ('service_period_end', models.DateField(db_column='SERVICE_PERIOD_END')),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], db_column='STATUS', default='PENDING', max_length=20)),
                ('verification_status', models.CharField(choices=[('MATCHED', 'MATCHED'), ('UNVERIFIED', 'UNVERIFIED'), ('MISMATCHED', 'MISMATCHED')], db_column='VERIFICATION_STATUS', default='UNVERIFIED', max_length=20)),
                ('verification_notes', models.TextField(blank=True, db_column='VERIFICATION_NOTES', null=True)),
                ('verified_at', models.DateTimeField(blank=True, db_column='VERIFIED_AT', null=True)),
                ('remarks', models.TextField(blank=True, db_column='NOTES', null=True)),
                ('contractor', models.ForeignKey(db_column='CONTRACTOR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='contractor_invoice', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(db_column='SITE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='site_invoice', to='client.site')),
                ('submitted_by', models.ForeignKey(db_column='SUBMITTED_BY', on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_column='VERIFIED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'POC_INVOICE',
            },
        ),
    ]
