# Generated by Django 6.0.3 on 2026-09-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_clientinvoice_contractorinvoice_delete_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorinvoice',
            name='verification_status',
        ),
    ]
